### ISSUE TITLE
Error: MissingPluginException(No implementation found for method init on channel plugins.indoor.solutions/pusher)

### ISSUE THREAD

**Issue by eshun4** [ninjasolutions/flutter_pusher#18]
Error: MissingPluginException(No implementation found for method init on channel plugins.indoor.solutions/pusher)
    at Object.throw_ [as throw] (http://localhost:58193/dart_sdk.js:5348:11)
    at MethodChannel._invokeMethod (http://localhost:58193/packages/flutter/src/services/system_channels.dart.lib.js:962:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:58193/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:58193/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:58193/dart_sdk.js:34073:29)
at handleValueCallback (http://localhost:58193/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:58193/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:58193/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58193/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:58193/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:58193/dart_sdk.js:39380:13)
    at http://localhost:58193/dart_sdk.js:34887:9

**Comment by eshun4** [comment]
This is the error I get once I initialize pusher in my init method.
