### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel pusherStream)

### ISSUE THREAD

**Issue by canaan5** [ninjasolutions/flutter_pusher#5]
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel pusherStream:
MissingPluginException(No implementation found for method listen on channel pusherStream)

When the exception was thrown, this was the stack: 
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)
#8      Pusher.init (package:pusher_websocket_flutter/pusher.dart:29:44)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Stinger101** [comment]
I had the same issue too. Were you able to solve it?

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel plugins.indoor.solutions/pusherStream:
MissingPluginException(No implementation found for method listen on channel plugins.indoor.solutions/pusherStream)

When the exception was thrown, this was the stack: 
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)
#8      Pusher.init (package:flutter_pusher/pusher.dart:40:44)

**Comment by Stinger101** [comment]
I found the solution, I stopped hot reloading and installed the app again. It worked.

**Comment by aslami-dev** [comment]
I have same problem!!!...there is a solution for this?
